
theme = "onedark"

[editor]
middle-click-paste = false
# bufferline = "always"
color-modes = true
cursorline = true
end-of-line-diagnostics = "hint" # works in-tandem with `editor.inline-diagnostics` options

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator", "version-control"]

[editor.lsp]
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 0

[editor.gutters]
layout = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]

# [editor.soft-wrap]
# enable = true
# max-wrap = 25 # increase value to reduce forced mid-word wrapping
# max-indent-retain = 0
# wrap-indicator = ""  # set wrap-indicator to "" to hide it

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

