#!/bin/sh

# Checks if the machine has a command available. First argument is the name of the command, second is the name of the package (optional).

cmd=$1

if [ -z "$2" ]; then
  pkg=$cmd
else
  pkg=$2
fi

if ! command -v $cmd &> /dev/null
then
  printf "\033[1;33mWARNING\033[0m: $pkg does not appear to be installed on this machine.\n"
  exit 1
fi

