#!/bin/sh

system=(

# Desktop Environment
hyprland # Goated Compositor
waybar # Status Bar
fuzzel # App Launcher
swaybg # BG utility (hyprbg is a memory hog)
swaync # Notifications daemon
# kanshi # Display output management
wl-clipboard # Clipboard
brightnessctl # Display brightness

# Theming
papirus-icon-theme # Icons
ttf-jetbrains-mono-nerd # Font
noto-fonts # Emojis and stuff
noto-fonts-cjk # Eastern languages

# Commandline Utils
man-pages
tree
less
ripgrep
usbutils # Provides stuff like lsusb
btop # Task management
fastfetch # You already know ;)
gdu # Totally goated disk usage analyzer
yazi # Terminal file manager

# Basic Utils
imv # Image Viewer
grim # Screenshot utility
slurp # Screen grabber (helps grim)
mpv # Video Player

# GUI programs
ghostty # Terminal
firefox
nwg-look # GTK configurer
pavucontrol # Audio mixer
  pipewire-pulse # Compat between Pipewire and PulseAudio
thunar # File manager
  gvfs # Trashbin, USB devices
  exfatprogs # exFAT Partition scheme
xarchiver # Archiver tool
  p7zip # 7-zip compat
pinta # Simple paint tool
guvcview # Camera program
zbar # QR Code/Barcode reader
obsidian # Notes app
discord # Communications app

# Software development
neovim # Terminal editor
tinyxxd # Hex dump tool
zed # GUI edior
git # Version Control System

# Bluetooth packages
blueman

ntfs-3g # NT Filesystem Support
)

aur=(
github-desktop-bin
hyprshot
mcpelauncher-ui # Minecraft launcher
onedrive-abraunegg # CLI OneDrive client
)

obs_studio=(
obs-studio
xdg-desktop-portal-hyprland # Required for screen recording
)

flutter_android=(
flutter # AUR - NOTE: paru won't update unless passed the -d flag (skip dependency checking)
android-studio # AUR
android-udev # Allows ADB in user mode
)

dioxus_desktop_native=(
webkit2gtk-4.1
xdotool
)

for item in "${system[@]}"; do
  echo "$item"
done

