[font]
size = 10.0

[font.normal]
family = "JetBrainsMono Nerd font"
style = "Regular"

[window]

dimensions = { columns = 92, lines = 28}
opacity = 0.8
title = "Terminal"
resize_increments = false

# Default colors
[colors.primary]
background = '#111111'
foreground = '#D0CFCC'


# # Normal colors
[colors.normal]
black   = '#000000'
red     = '#C01C28'
green   = '#26A269'
yellow  = '#A2734C'
blue    = '#12488B'
magenta = '#A347BA'
cyan    = '#2AA1B3'
white   = '#D0CFCC'

# Bright colors
[colors.bright]
black   = '#5E5C64'
red     = '#F66151'
green   = '#33D17A'
yellow  = '#E9AD0C'
blue    = '#2A7BDE'
magenta = '#C061CB'
cyan    = '#33C7DE'
white   = '#FFFFFF'

[cursor]

style = { shape = "Beam", blinking = "On" }
blink_interval = 500
thickness = 0.2

[mouse]

hide_when_typing = true



